### PR TITLE
Bump csi-provisioner to v3.4.1

### PR DESCRIPTION
**Pull request by ejweber**
#5672

### CODE REVIEW

**Comment by ejweber** [comment]
It looks like we need to update other sidecars as well (all of the versions we are using have fallen out of support). There are some interdependencies between versions that I want to be careful with (and it is probably best to handle all of it at once). I'll create a couple of new PRs tomorrow that handle this better. Apologies for the churn.

**Comment by PhanLe1010** [comment]
Besides of longhorn/longhorn repo, we need to update the version in longhorn/longhorn-manager as well: https://github.com/longhorn/longhorn-manager/blob/66e31ba3e7ae77779a9ba3b5bf6695e39b9f5f68/csi/deployment.go#L23-L28

**Comment by ejweber** [comment]
Good catch, @PhanLe1010, and thanks for your comment. Unfortunately, I didn't look closely enough at how the driver was being deployed on my initial pass. I assumed the Helm chart was taking the provided values and doing the deployment of the driver (using a template or templates) directly. I see now that Helm instead deploys a longhorn-manager-deployer Pod that actually does the deployment (with the "longhorn-manager csi ..." command). Eventually, on uninstall, Helm deploys a longhorn-uninstall Pod (with the "longhorn-manager uninstall" command) that reverses it.

It's clear to me now why the additional values you pointed out exist. However, it's a bit unclear why the longhorn-manager executable itself must be responsible for creating and cleaning up the CSI components instead of the overarching deployment mechanism (e.g. Helm). Do you or @innobead have any insight to share on this? Do we support a workflow in which a user might directly execute longhorn-manager to install or uninstall CSI components? (This certainly isn't necessary for me to prepare a new PR, but it might help shape the way I think about proposed changes moving forward.)

**Comment by PhanLe1010** [comment]
Discussed with @ejweber: A few reasons that we are using `longhorn-manager` image in the driver-deployer to deploy the `csi-xxx` components instead of using the traditional Helm template are:
1. The driver-deployer can dynamically discover the kubelet directory and deploy the `csi-xxx` to connect to the correct the Unix domain socket
2. The driver watches the `settings.longhorn.io` like priorityClass, tolerations,... and sets them to `csi-xxx` deployment

**Pull request closed without merging**
