### PR TITLE
Introducing Longhorn Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Longhorn Guru](https://gurubase.io/g/longhorn) to Gurubase. Longhorn Guru uses the data from this repo and data from the [docs](https://longhorn.io/docs/1.7.2/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Longhorn Guru", which highlights that Longhorn now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Longhorn Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by derekbit** [comment]
cc @innobead @longhorn/maintainer

**Comment by derekbit** [comment]
@kursataktas Thank you for sharing this interesting application and contribution. However, I don't recommend including the Gurubase link in the Longhorn README.md. While the resource might be helpful to some users, it is not maintained by the Longhorn team. We cannot guarantee the accuracy of the LLM’s outputs, which could create a false impression and potentially mislead users. 

cc @innobead @longhorn/maintainer

**Comment by derekbit** [comment]
@kursataktas Will the gurubase automatically collect and analyze the latest tickets and docs in https://github.com/longhorn/longhorn/ and https://longhorn.io/?

**Comment by kursataktas** [comment]
Hi @derekbit, thanks for the review.

Just to clarify, Gurubase doesn't currently analyze issues or discussions on GitHub. We do have a plan for this, but it’s not ready yet. On the other hand, I was planning to manually update the sources by monitoring the docs if we add a badge.

Additionally, we will release a feature that will allow repository maintainers to manage their Gurus on Gurubase. This feature will enable you to edit data sources and view analytics on the types of questions users are asking, among other insights. Do you think this would address the concern you mentioned?

**Pull request closed without merging**
