### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aioue**
Add arguments for helm3

### CODE REVIEW

**Comment by yasker** [comment]
@aioue , thanks for contributing! Can you add your `signed-off` per https://github.com/longhorn/longhorn/blob/master/CONTRIBUTING.md#dco-sign-off ? Thanks!

**Comment by meldafrawi** [comment]
@aioue 

According to helm v3 docs: https://helm.sh/docs/faq/#automatically-creating-namespaces
We need to manually create `longhorn-system` namespace before installing Longhorn.

**Comment by aioue** [comment]
Add namespace creation and commit with Signed-off message.

**Comment by yasker** [comment]
@aioue 

Can you move the comment of Helm 2/Helm 3 to out of the quote? It's clearer that way, so the user only need to copy what's inside the quote for the relative helm version.

Also, can you squash all the commits into one? The `sign-off` needs to be added to every commit.

Thanks!

**Comment by aioue** [comment]
This might be slightly beyond my current git-fu. Since it's only a few lines in the readme, I'm happy to close this request and for you to copy it over in the format you prefer?

**Comment by yasker** [comment]
@aioue In fact it's not hard to do squash. You can use `git rebase -i` and use `squash` option to squash the commits into one commit.

You can reach me in the Rancher User or CNCF or Kubernetes slack. I would be happy to help you to sort this out.

**Comment by yasker** [comment]
Hi @aioue ,

I've submitted PR https://github.com/longhorn/longhorn/pull/1080 to replace this one. Let me know if it looks good to you.

**Comment by yasker** [comment]
Hi @aioue 

We haven't heard from you yet. Since you mentioned you're happy to let us handle this in https://github.com/longhorn/longhorn/pull/1041#issuecomment-586954594 , we will merge #1080 and close this PR then.

Thanks!

**Pull request closed without merging**
