### PR TITLE
/var/run/ - mountPropagation: Bidirectional

### PR DESCRIPTION
**Pull request by STASiAN**
this fix related issue with containerd
https://github.com/containerd/containerd/issues/3667

### CODE REVIEW

**Comment by yasker** [comment]
@STASiAN Thanks for the PR. Can you file an issue too so we can know what's the problem and reproduce steps, then our QA would be able to verify the fix?

**Comment by jdunhamvrtx** [comment]
Can I lobby for this to make it in the next release. I'm affected by this and the rancher version of the bug , rancher/#26506.

**Comment by yasker** [comment]
@jdunhamvrtx Sure. Can you help us to understand what's the impact? And what's the reproduce steps for the issue? We need to have an issue filed for this to be tracked.

**Comment by jdunhamvrtx** [comment]
Hey @yasker : This is a config enhancement for containerd as I read things. The issue is described here,

https://github.com/containerd/containerd/issues/3667

If no options are specified for mountPropagation I believe it's mounted as private and get's stuck when the pod terminates. I think the issue is conflict b/w the ver of containerd and iproute packages. It affects K3S and RHEL 7.8 (no apparmor) at least. This PR is to provide the correct option to LH and there is another PR for rancher and cattle-node-agent template   to do the same,

https://github.com/rancher/rancher/issues/26506

Looking at the patches though, they are using two different options (BiDirectional vs, HostToContainer). I'm not sure if this was a targeted choice for each project or not.

**Comment by yasker** [comment]
Thanks for the explaination @jdunhamvrtx 

@STASiAN can you help to create another PR to https://github.com/longhorn/longhorn-manager/blob/master/deploy/install/02-components/01-manager.yaml ? We need to update both chart and yaml (which is in the Longhorn manager).

I can merge those two PRs but since we don't have the detail reproduce steps (e.g. which version of containerd it affected, what steps our QA needs to take to reproduce and verify the fix), we cannot validate the fix after merged it. So if it's OK with you, I am fine with merging the PRs.

**Comment by jdunhamvrtx** [comment]
I'm affected by this with versions,

- containerd : 1.2.10
- OS : RHEL 7.8 3.10.0-1127.10.1.el7.x86_64
- iproute2 : iproute2-ss170501 4.11.0
- K3S : 1.18.6+k3s1

RHEL put out an advisory about iproute creating netns mounts with this issue in 2014. 
https://bugzilla.redhat.com/show_bug.cgi?id=1062685
They emphasized a need to create the mounts as shared (not private)

I think to solve this it needs to be patched in LH and Rancher.

**Comment by STASiAN** [comment]
@yasker 
PR for longhorn-manager: https://github.com/longhorn/longhorn-manager/pull/649

My Software versions:
- CentOS Linux release 7.8.2003 (Core)
- kernel-3.10.0-1127.10.1.el7.x86_64
- containerd.io-1.2.13-3.2.el7.x86_64
- iproute-4.11.0-25.el7_7.2.x86_64

logs form Kubelet:
https://termbin.com/d3s3
```
# ip netns list
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
RTNETLINK answers: Invalid argument
cni-151bad8d-23b9-7b3f-0b30-8f109551e59a (id: 21)
cni-0564ab9e-4e12-6e93-0f18-c8f5c7a2407d (id: 20)
cni-bbfa5895-0c8a-29a7-94c0-4a5631c23fee (id: 19)
cni-db479937-ede0-9b35-c456-5339b3af818b (id: 18)
cni-f768a617-e61c-7862-c787-b9f4b1441e41 (id: 17)
cni-762aeab8-a151-4fa2-4162-70193931ba44 (id: 15)
cni-a0dafdaa-bd07-85ec-4d45-0eafe62e670d (id: 14)
cni-ac21b658-c580-5339-4857-26d0d31ee595 (id: 11)
cni-ca8dd84c-f1fe-288a-abe0-94dcbf5ddf59 (id: 9)
cni-644021f6-8f9a-cc1b-b384-a92d9ffc9dba (id: 8)
cni-e3d851ba-84bf-ee28-d494-332c08102dd2 (id: 7)
cni-2269098b-96a3-dd8c-e848-1e673d255219 (id: 5)
cni-007a5ce6-a472-6f72-b623-4fbe9cc9ca5c (id: 4)
cni-e6bb5e91-ad3d-85c8-0880-d8008b28eb59 (id: 2)
cni-b9715d72-dadd-d604-1243-b605c40145aa (id: 3)
cni-b39c2d11-9d87-8b0a-7452-40eff82b6617 (id: 1)
cni-28d749cb-128d-c3b2-604f-63f7978725a1 (id: 0)
RTNETLINK answers: Invalid argument
cni-6e22ff07-e987-1308-8ca4-de39dddb5843
RTNETLINK answers: Invalid argument
cni-9c6aa9ef-1e36-2ff4-9af4-92dc4f947b1d
RTNETLINK answers: Invalid argument
cni-feaf64b0-c50e-e6b7-1d75-12be0e9f034b
RTNETLINK answers: Invalid argument
cni-ac3cbd10-23b9-a651-b002-7fa30f20a67d
RTNETLINK answers: Invalid argument
cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51

# ip netns 2>1|grep cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51
cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51

# ip netns exec cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51 ip a
setting the network namespace "cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51" failed: Invalid argument

# grep cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51 /proc/*/mountinfo
/proc/14027/mountinfo:1306 1304 0:3 / /run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51 rw,nosuid,nodev,noexec,relatime - proc proc rw

# ps aux |grep 14027
root     14027  0.5  0.3 139308 49332 ?        Ssl  Jul14   5:56 longhorn-manager -d daemon --engine-image longhornio/longhorn-engine:v0.8.0 --instance-manager-image longhornio/longhorn-instance-manager:v1_20200301 --manager-image longhornio/longhorn-manager:v0.8.0 --service-account longhorn-service-account

# rm -rf /run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51
rm: cannot remove '/run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51': Device or resource busy
```
exec into container and perform unmount fix the problem
```
root@longhorn-manager-4pfww:/# umount /run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51
root@longhorn-manager-4pfww:/# umount /run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51
umount: /run/netns/cni-cf8b5cf5-3bfa-b027-bf1d-642e84ad7b51: no mount point specified.
```

How to reproduce:
Setup k8s on centos 7 with https://kubespray.io/
setup longhorn via helm
install any other software like metrics-server via helm
try to delete scale/downscale deployments
or just delete pods
 
see containerd related issue

**Pull request merged**
