### PR TITLE
chore(support-bundle): version bump

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5614

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM. Will merge when the image is ready.

**Comment by c3y1huang** [comment]
@yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.23](https://registry.hub.docker.com/layers/rancher/support-bundle-kit/v0.0.23/images/sha256-c47053a190cbf6e51d74b4d4cf134b6c7c4ff7346feb90f601765efdc10ef2d5?context=explore) to longhornio, thanks.

**Comment by innobead** [comment]
@yangchiu Can we extend https://ci.longhorn.io/job/private/job/mirror-csi-images later to support downloading this, so next time, engineers can trigger on their own?

**Comment by yangchiu** [comment]
> @yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.23](https://registry.hub.docker.com/layers/rancher/support-bundle-kit/v0.0.23/images/sha256-c47053a190cbf6e51d74b4d4cf134b6c7c4ff7346feb90f601765efdc10ef2d5?context=explore) to longhornio, thanks.

image mirrored: https://hub.docker.com/layers/longhornio/support-bundle-kit/v0.0.23/images/sha256-c47053a190cbf6e51d74b4d4cf134b6c7c4ff7346feb90f601765efdc10ef2d5?context=explore

**Comment by yangchiu** [comment]
> @yangchiu Can we extend https://ci.longhorn.io/job/private/job/mirror-csi-images later to support downloading this, so next time, engineers can trigger on their own?

support-bundle-kit is not intended to be keeping upgraded like csi components, right? We keep doing this now only because it's buggy at this moment.

**Comment by innobead** [comment]
> support-bundle-kit is not intended to be keeping upgraded like csi components, right? We keep doing this now only because it's buggy at this moment.

Good ask. Exactly, but are there any concerns to add this to the mirror job? I feel we can make the mirror job general. For sure, right now we only need CSI and support-bundle only. 

This is not a high priority, but we can tackle this later if needed.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
