### PR TITLE
chore(support-bundle): version bump

### PR DESCRIPTION
**Pull request by c3y1huang**
For [fix](https://github.com/rancher/support-bundle-kit/pull/71).

Ref: https://github.com/longhorn/longhorn/issues/5614

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by c3y1huang** [comment]
@yangchiu we need a mirrored image of [rancher/support-bundle-kit:v0.0.24](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.24/images/sha256-7545a151aeea1653423a81cbf3fd01c8a50d4b42528833a280ddd7aeb5e7cba1?context=explore). Thanks!

**Comment by yangchiu** [comment]
> @yangchiu we need a mirrored image of [rancher/support-bundle-kit:v0.0.24](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.24/images/sha256-7545a151aeea1653423a81cbf3fd01c8a50d4b42528833a280ddd7aeb5e7cba1?context=explore). Thanks!

done! https://hub.docker.com/layers/longhornio/support-bundle-kit/v0.0.24/images/sha256-7545a151aeea1653423a81cbf3fd01c8a50d4b42528833a280ddd7aeb5e7cba1?context=explore

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3504/

We also need to merge [the test case fix](https://github.com/longhorn/longhorn-tests/pull/1311).

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
