### PR TITLE
Bump sidecar container versions for csi-lib-utils issue

### PR DESCRIPTION
**Pull request by ejweber**
#### Which issue(s) this PR fixes:

longhorn/longhorn#8427

#### What this PR does / why we need it:

See the linked issue for the upstream context.

### CODE REVIEW

**Comment by ejweber** [comment]
Regression testing at: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6762/.

**Comment by ejweber** [comment]
Tested the fix using steps from https://github.com/longhorn/longhorn/issues/8427#issuecomment-2089153745 and csi-attacher (but not csi-provisioner) still seems to be vulnerable. Need to investigate further.

**Comment by ejweber** [comment]
> Tested the fix using steps from https://github.com/longhorn/longhorn/issues/8427#issuecomment-2089153745 and csi-attacher (but not csi-provisioner) still seems to be vulnerable. Need to investigate further.

I could not reproduce this. All other attempts worked well.

**Comment by ejweber** [comment]
> Regression testing at: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6762/.

Passed except for https://github.com/longhorn/longhorn/issues/8488.

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by ejweber** [comment]
@mergify backport v1.6.x v1.5.x

**Pull request merged**
