### PR TITLE
deploy, scripts: provide list of images and scripts to pull and push all Longhorn component images to user provided registry

### PR DESCRIPTION
**Pull request by PhanLe1010**
This help to remove the extra dependency on different container image registry. Docker Hub now holds all Longhorn components' images. Also, users can easily pull all the necessary images to their air-gap environment.
There are 3 different images files:
1. `longhorn-images-release.txt` (use when release a new version, current value is `v1.0.1`)
1. `longhorn-images-dev.txt` (For dev to pull/push with `master` images)
1. `longhorn-images.txt` (For end-user to pull/push `stable release` images,  current value is `v1.0.1`)

longhorn/longhorn#1419

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Do you mean the name of the script like this fix?

**Comment by yasker** [comment]
This change should be made against the v1.0.1 branch instead of master...

**Comment by yasker** [comment]
I've reverted the change in master. Can you resubmit a PR against v1.0.1 branch?

**Comment by PhanLe1010** [comment]
New PR at https://github.com/longhorn/longhorn/pull/1583

**Pull request merged**
