### PR TITLE
chore(ci): update status and sprint of community issues if non-longhorn user comments

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn#9411

#### What this PR does / why we need it:

- Add a check for teps.is_longhorn_member.outcome == 'success' to prevent errors caused by unrecognized users, such as github-action[bot].
- Move an issue to `New` if it is newly created
- Move an issue to `In Progress` status if a non-longhorn user replies. 
- Move an issue to `Resolved` if a milestone is set
- Move an issue to `Closed` if `wontfix` or `invalid` label is set

image

### CODE REVIEW

**Comment by innobead** [comment]
cc @bk201

**Comment by derekbit** [comment]
Ready for review. cc @innobead

**Comment by innobead** [comment]
>Move an issue to In Progress status if a non-longhorn user replies. 

Also, move to the current sprint.

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
