### PR TITLE
crd: add instanceManager.spec.backendStoreDriver

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#6984

### CODE REVIEW

**Comment by innobead** [comment]
> #984

@derekbit the issue number is incorrect?

**Comment by derekbit** [comment]
> > #984
> 
> @derekbit the issue number is incorrect?

Fixed. Thank you.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@derekbit this is the same as https://github.com/longhorn/longhorn/pull/7358/files?

**Comment by derekbit** [comment]
> @derekbit this is the same as https://github.com/longhorn/longhorn/pull/7358/files?

Yes, this can be closed. Thank you.

**Pull request closed without merging**
