### PR TITLE
Mirror the quay.io/openshift/origin-oauth-proxy image to Longhorn repo and update the chart

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#8329

### CODE REVIEW

**Review by derekbit — APPROVED** [review]
LGTM

**Review by innobead — COMMENTED** [review]
LGTM

**Comment by derekbit** [comment]
@PhanLe1010 
The PR is for master-head. The rancher chart release targets longhorn v1.6.1 as the info in https://github.com/rancher/charts/pull/3753. Should it be backported to v1.6.x?

**Comment by PhanLe1010** [comment]
> @PhanLe1010 The PR is for master-head. The rancher chart release targets longhorn v1.6.1 as the info in [rancher/charts#3753](https://github.com/rancher/charts/pull/3753). Should it be backported to v1.6.x?

You are right! Derek, I will do the backport tomorrow with US team. Thanks a lot!

**Comment by PhanLe1010** [comment]
@mergify backport v1.6.x

**Pull request merged**
