### PR TITLE
Add ReplicaDiskSoftAntiAffinity setting

### PR DESCRIPTION
**Pull request by ejweber**
#3823

### CODE REVIEW

**Review by james-munson — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Merge this after the manager PR is merged.

**Comment by ejweber** [comment]
This one needs merging now. 

cc @innobead or @PhanLe1010

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Pull request merged**
