### PR TITLE
Allow user to specify priority class and tolerations for Longhorn UI, Driver, Manager

### PR DESCRIPTION
**Pull request by PhanLe1010**
Now that we only watch/update managed components, we should allow user to specify Helm values for user deployed components (manager, driver, UI).

longhorn/longhorn#2120

### CODE REVIEW

**Comment by shuo-wu** [comment]
One quick question, do we allow users to set these when using Rancher APP to deploy Longhorn?

**Comment by PhanLe1010** [comment]
@shuo-wu 

Good question. The answer is not directly but there is a workaround. 
Sice toleration is an array input, Rancher's `question.yaml` doesn't support array input. Users can workaround by doing `Edit as YAML` in Rancher UI instead. More details at https://github.com/rancher/rancher/issues/24918. I learn this info from you :)

**Review by shuo-wu — APPROVED** [review]

**Comment by PhanLe1010** [comment]
ping @shuo-wu 
Can we merge this one

**Review by shuo-wu — APPROVED** [review]

**Comment by shuo-wu** [comment]
Sorry. Can you directly rebase your branch? If I rebase the branch via Github UI, there will be an extra commit.

**Review by innobead — APPROVED** [review]

**Comment by PhanLe1010** [comment]
@shuo-wu  
Rebased

**Pull request merged**
