### PR TITLE
fix(chart): update default setting log level

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/6257

### CODE REVIEW

**Review by derekbit — APPROVED** [review]

**Comment by shuo-wu** [comment]
Do we need to change this after fixing the PVC recurring job label issue?

**Comment by c3y1huang** [comment]
> Do we need to change this after fixing the PVC recurring job label issue?

We've updated the log level to "info" so the recurring job source label log at the "debug" level doesn't overwhelm when the cluster is at the default log level setting.

So this is to reflect on the log level change. Any concerns?

**Comment by shuo-wu** [comment]
OK. Just noticed that the log level is changed to `debug` rather than `trace`.

As we discussed before, some of the important logs were level `debug`. Suppressing them would make the support bundle debugging more difficult. 
Not sure we already tune all logs and it's fine to change the default level to `debug` now. cc @derekbit

**Comment by derekbit** [comment]
Most of debug level logs are adjusted in https://github.com/longhorn/longhorn-manager/pull/2059 and previous commits.
The remaining ones are "requeue....", "...backoff" and so on.
cc @shuo-wu 

image

image

**Review by ChanYiLin — APPROVED** [review]

**Comment by innobead** [comment]
@shuo-wu any concern here?

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Pull request merged**
