### PR TITLE
Chart: explicitly set default fsType to EXT4

### PR DESCRIPTION
**Pull request by PhanLe1010**
This allow Kubernetes to properly changes the volume ownership
and permissions when user specify fsGroup in workload pod

longhorn/longhorn#2964

### CODE REVIEW

**Review by shuo-wu — COMMENTED** [review]
Quick question: If the filesystem type is not set in the CSI provisioner, does adding this field in StorageClass work?

**Comment by PhanLe1010** [comment]
> Quick question: If the filesystem type is not set in the CSI provisioner, does adding this field in StorageClass work?

Yeah. CSI provisioner check and see that the SC has `fsType` so it use it regardless of whether we set the default fs in csi provisioner

**Comment by shuo-wu** [comment]
> > Quick question: If the filesystem type is not set in the CSI provisioner, does adding this field in StorageClass work?
> 
> Yeah. CSI provisioner checks and see that the SC has `fsType` so it uses it regardless of whether we set the default fs in csi provisioner

Great. Then please:
1. mention this as a workaround in both https://github.com/longhorn/longhorn/issues/2964#issuecomment-910969543 and the Slack channel.
2. Update the default StorageClass and the example StorageClass

**Review by shuo-wu — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Comment by PhanLe1010** [comment]
@shuo-wu we discussed in Slack that we don't want to recommend user to change longhorn SC so we don't want to mention this workaround. 


I will update the SC example.

**Pull request merged**
