### PR TITLE
chart: Add "Allow Collecting Longhorn Usage Metrics" to settings

### PR DESCRIPTION
**Pull request by yardenshoham**
This setting was added in https://github.com/longhorn/longhorn-manager/pull/1891 but is not exposed in the helm chart.

Reference:
- https://github.com/longhorn/longhorn/issues/5235
- Closes https://github.com/longhorn/longhorn/issues/7050

### CODE REVIEW

**Review by c3y1huang — APPROVED** [review]
lgtm, thank you!

**Comment by derekbit** [comment]
@yardenshoham 

Can you help update https://github.com/longhorn/longhorn/blob/master/chart/templates/default-setting.yaml as well? Thank you.

**Review by innobead — CHANGES_REQUESTED** [review]
LGTM, but also need to update [README.md](https://github.com/longhorn/longhorn/blob/master/chart/README.md) and also [helm values](https://github.com/longhorn/website/blob/master/content/docs/1.6.0/references/helm-values.md) on the website. 

@yardenshoham Can you follow https://github.com/longhorn/longhorn/wiki/document-convention#generate-readme to update them? Thanks. 

@ChanYiLin Please help review this.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@ChanYiLin before merging this, please help review and verify it. Thanks. 

We also need to update https://longhorn.io/docs/1.6.0/references/helm-values/.

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Pull request merged**
