### PR TITLE
doc(lep): update system backup lep for backup bacingimages

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: https://github.com/longhorn/longhorn/issues/5085

We now support backup backingimages when doing system backup
Update the lep.

### CODE REVIEW

**Review by c3y1huang — COMMENTED** [review]
Could you also check the `Non-goals [optional]` section regarding the backing image? It seems like it could be removed.

**Comment by ChanYiLin** [comment]
> Could you also check the `Non-goals [optional]` section regarding the backing image? It seems like it could be removed.

Hi @c3y1huang 
Removed, thanks

**Review by c3y1huang — APPROVED** [review]

**Review by derekbit — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
