### PR TITLE
chore(release): add v1.7.2 as stable

### PR DESCRIPTION
**Pull request by macedogm**
#### Which issue(s) this PR fixes:

Issue #

#### What this PR does / why we need it:
Add Longhorn release v1.7.2 as the stable for v1.7 branch.

### CODE REVIEW

**Comment by derekbit** [comment]
@macedogm @innobead Let's mark it as stable this Friday. WDYT?

**Comment by innobead** [comment]
> @macedogm @innobead Let's mark it as stable this Friday. WDYT?

Yes. We need to wait one week for community feedback, especially regarding the upgrade, before making version 1.7.2 stable officially.

**Comment by macedogm** [comment]
@derekbit and @innobead thanks for the quick review. Apologies, I wasn't aware of this rule and jumped too quickly on this one. Should I close the PR?

**Comment by innobead** [comment]
@macedogm no worries. let's keep this open and merge this until this Friday if everything is ready.

**Review by innobead — APPROVED** [review]

**Review by derekbit — APPROVED** [review]

**Pull request merged**
