### PR TITLE
Rename yml to yaml

### PR DESCRIPTION
**Pull request by dp-42**
Hello,

for consistency reasons I have changed all `yml` files to `yaml` files.

Also discussed in https://github.com/longhorn/longhorn/issues/3102.

Kind regards!

### CODE REVIEW

**Review by jenting — APPROVED** [review]
LGTM.

I think the upgrade should work well.

**Comment by jenting** [comment]
@dp-42 could you please fix the conflicts? Thank u.

**Comment by dp-42** [comment]
@jenting Many thanks for looking in this - I have resolved the conflicts...

**Comment by dp-42** [comment]
Friendly reminder at @shuo-wu @jenting - is there anything that is blocking this from merging?

**Comment by jenting** [comment]
I've approved it :wink:

**Review by shuo-wu — APPROVED** [review]

**Comment by innobead** [comment]
@dp-42 Thanks for your contribution! Need your help to resolve the conflict first caused by the recent release merge. After that, this PR will be merged.

**Comment by dp-42** [comment]
@innobead Thank you very much! I have solved the conflict.

**Pull request merged**
