### PR TITLE
Fix `removeSnapshotsDuringFilesystemTrim` not being used in helm chart

### PR DESCRIPTION
**Pull request by yardenshoham**
Also ran `./scripts/generate-longhorn-yaml.sh`

#### Which issue(s) this PR fixes:
Issue https://github.com/longhorn/longhorn/issues/7909

### CODE REVIEW

**Comment by ejweber** [comment]
Tested with steps from https://github.com/longhorn/longhorn/issues/7909#issuecomment-1948634684.

Default case:

```
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        fsType: "ext4"
        dataLocality: "disabled"
        unmapMarkSnapChainRemoved: "ignored"
```

Non-default case:

```
parameters:
  dataLocality: disabled
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: enabled
```

**Review by ejweber — APPROVED** [review]
LGTM.

**Review by derekbit — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Comment by ejweber** [comment]
@mergify backport v1.6.x v1.4.x

Holding off on v1.5.x until v1.5.4 release.

**Comment by ejweber** [comment]
@mergify backport v1.5.x

**Pull request merged**
