### PR TITLE
Update version number 1.2.6 in question.yaml

### PR DESCRIPTION
**Pull request by weizhe0422**
Signed-off-by: Ray Chang <ray.chang@suse.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Review by innobead — COMMENTED** [review]
@weizhe0422 Need to update attacher and node driver to rollback @PhanLe1010 incorrect vomit before. Thanks.

**Comment by weizhe0422** [comment]
Okay, I will check related files has correct image tag both on longhorn and longhorn-manager repos. Then create PR to update it.

**Comment by innobead** [comment]
U just need to update questions in this repo now because @PhanLe1010 has clarified the wrong backport in questions yaml.

**Comment by PhanLe1010** [comment]
@weizhe0422 The only thing left is update this `variable: image.csi.attacher.tag` to `v3.2.1` and `image.csi.nodeDriverRegistrar.tag` to `v2.3.0` in this PR

**Comment by weizhe0422** [comment]
Got it and I will create another PR to update version tag in question.yaml.

**Pull request merged**
