### PR TITLE
Add longhorn-system namespace to installer daemonsets

### PR DESCRIPTION
**Pull request by samtudor0112**
#### Which issue(s) this PR fixes:
Issue https://github.com/longhorn/longhorn/issues/8855

#### What this PR does / why we need it:
Add longhorn-system namespace to installer daemonsets

### CODE REVIEW

**Comment by samtudor0112** [comment]
Works
image

**Comment by derekbit** [comment]
@PhanLe1010 @ejweber @shuo-wu Do you think if we need the change?

**Comment by derekbit** [comment]
@PhanLe1010 @ejweber @shuo-wu Do  @innobead  you think if we need the change?

**Comment by ejweber** [comment]
> @PhanLe1010 @ejweber @shuo-wu Do @innobead you think if we need the change?

I don't have much of a preference. Either `longhorn-system` or `default` seem fine to me. I lean a slight bit toward @samtudor0112's point of view because:

1. I think if I was creating these from scratch today, I would put them in the `longhorn-system` namespace.
2. Whether or not is is necessarily intended, I think the DaemonSets can be used in the way described in https://github.com/longhorn/longhorn/issues/8855#issuecomment-2198439492. (They can be left active in the cluster to ensure newly added nodes get dependencies installed.) In that case, it is better for them not to be in the `default` namespace.

I'll leave it to @derekbit or @innobead to make the call.

**Review by derekbit — APPROVED** [review]

**Comment by samtudor0112** [comment]
Anything further needs to be done before this is merged?

**Comment by samtudor0112** [comment]
Can this be merged yet?

**Review by ejweber — APPROVED** [review]

**Comment by derekbit** [comment]
@samtudor0112 
Thanks for your contribution.

**Pull request merged**
