### PR TITLE
feat(support-bundle): version bump

### PR DESCRIPTION
**Pull request by c3y1huang**
~https://github.com/longhorn/longhorn/issues/6338~
https://github.com/longhorn/longhorn/issues/6544

### CODE REVIEW

**Comment by c3y1huang** [comment]
This is blocked by https://github.com/rancher/support-bundle-kit/pull/77.

**Review by innobead — APPROVED** [review]

**Comment by c3y1huang** [comment]
@yangchiu could you help to mirror [rancher/support-bundle-kit:v0.0.27](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.27/images/sha256-a5c26e42a9017bd768651200da978ca8cba7b747fc42b7e3315a83f7010cf76d?context=explore) to longhornio? thank you.

**Comment by yangchiu** [comment]
image mirrored: https://hub.docker.com/layers/longhornio/support-bundle-kit/v0.0.27/images/sha256-a5c26e42a9017bd768651200da978ca8cba7b747fc42b7e3315a83f7010cf76d?context=explore

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
