### PR TITLE
Add ServiceMonitor in helm chart

### PR DESCRIPTION
**Pull request by enrico9034**
To ensure you can create the service monitor without having to deploy it manually after installation, I added a values metrics.serviceMonitor.enabled. The default values is false, but if set to true it creates the service monitor according to the documentation.

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM.

@yangchiu Please help verify this PR and approve if it works as expected. 

cc @longhorn/qa

**Comment by innobead** [comment]
@roger-ryao Please help verify this PR and approve it if all good. Thanks.

**Comment by innobead** [comment]
@mantissahz the issue of this PR was assigned to you. Please help resolve the conflict and move this PR ready for merging. Thanks.

**Comment by mantissahz** [comment]
@innobead, @enrico9034,
Fixed the conflicted file.

**Comment by mantissahz** [comment]
Update:
Verified PR in my local cluster.

**Comment by enrico9034** [comment]
@mantissahz I aligned the MR with the master, Can you please review it again and if possible merge it?

**Comment by raelix** [comment]
Any updates?

**Comment by mantissahz** [comment]
@enrico9034 there are still some conflicts, could you fix them please?

**Comment by enrico9034** [comment]
> @enrico9034 there are still some conflicts, could you fix them please?

Done

**Comment by raelix** [comment]
Hi @mantissahz this is pending from a long time, is there any chance to merge please?

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mantissahz Please help update the doc, https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update.

**Pull request merged**
