### PR TITLE
chore(support-bundle): version bump

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5614

### CODE REVIEW

**Comment by weizhe0422** [comment]
`v0.0.0.21` will also include [Longhorn #5670](https://github.com/longhorn/longhorn/issues/5670) fixes.

**Comment by c3y1huang** [comment]
@yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.22](https://registry.hub.docker.com/layers/rancher/support-bundle-kit/v0.0.22/images/sha256-acc4ed2cca0303beb54feafafed891f32389b29a50bac25523e7bce3c4cf73e8?context=explore) to longhornio. Thanks!

**Comment by yangchiu** [comment]
> @yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.22](https://registry.hub.docker.com/layers/rancher/support-bundle-kit/v0.0.22/images/sha256-acc4ed2cca0303beb54feafafed891f32389b29a50bac25523e7bce3c4cf73e8?context=explore) to longhornio. Thanks!

image mirrored https://hub.docker.com/layers/longhornio/support-bundle-kit/v0.0.22/images/sha256-acc4ed2cca0303beb54feafafed891f32389b29a50bac25523e7bce3c4cf73e8?context=explore

**Comment by c3y1huang** [comment]
Tests passed in my cluster, but somehow running in the regression pipeline seems to be hanging. Checking with @yangchiu .

**Comment by c3y1huang** [comment]
> Tests passed in my cluster, but somehow running in the regression pipeline seems to be hanging. Checking with @yangchiu .

After talking to @yangchiu , this is caused by the [node taints](https://github.com/longhorn/longhorn-tests/blob/master/test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_server.sh.tpl#L11) in the pipeline.

**Comment by c3y1huang** [comment]
Test result: https://github.com/longhorn/longhorn-manager/pull/1798#issuecomment-1499893248

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
