### PR TITLE
Fix some small errors on StorageClass NodeSelector.

### PR DESCRIPTION
**Pull request by james-munson**
For ticket #6392

### CODE REVIEW

**Review by ejweber — COMMENTED** [review]
LGTM

I would be curious to see a screenshot of what this looks like in the Rancher UI with the changes.

**Comment by james-munson** [comment]
Here's a screen shot from installing the amended Longhorn chart from my branch (note the "whith" changed to "with".  Most of the changes are less visible, but are for agreement with values.yaml.

Screenshot-Rancher-6392-questions-yaml

**Review by ejweber — APPROVED** [review]
Screenshot looks good and verified with @james-munson that the selector is now applied to the default storage class correctly when installing via Rancher.

Please update the [test steps](https://github.com/longhorn/longhorn/issues/6392#issuecomment-1652415733) to include that verification after installation.

**Comment by PhanLe1010** [comment]
Discussed with @james-munson, the node selector here is for volume's replica scheduling. The current description `We use NodeSelector when we want to bind PVC via StorageClass into desired mountpoint on the nodes tagged with its value` is a bit confusing. May be we should change it to mention that this is for replica scheduling logic

**Comment by PhanLe1010** [comment]
> Discussed with @james-munson, the node selector here is for volume's replica scheduling. The current description `We use NodeSelector when we want to bind PVC via StorageClass into desired mountpoint on the nodes tagged with its value` is a bit confusing. May be we should change it to mention that this is for replica scheduling logic

Let's do this in the ticket https://github.com/longhorn/longhorn/issues/4776

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Pull request merged**
