### PR TITLE
add manifest to install nfs using daemonset (#2033)

### PR DESCRIPTION
**Pull request by cclhsu**
#### Proposed Changes ####

1. Add manifest to install `nkfs-client` using deamonset/initcontainer

#### Types of Changes ####

New Feature.

#### Verification ####

1. Deploy RKE/K3S on Centos/Ubuntu/SLES15SP2 and Verify if containers run successfully on each node and installed package run successfully.

#### Linked Issues ####

Refs: #2033

#### Further Comments ####

None

Signed-off-by: cclhsu <clark.hsu@suse.com>

### CODE REVIEW

**Comment by yasker** [comment]
`nkfs-kernel-server`? Also, why NFS kernel server is required instead of NFS client?

**Comment by cclhsu** [comment]
> `nkfs-kernel-server`? Also, why NFS kernel server is required instead of NFS client?

I thought the node need to serve, but it was other way around.  I have updated the manifest and rebase for `v1.1.1`

**Comment by yasker** [comment]
Similar to https://github.com/longhorn/longhorn/pull/2210 , this PR should be made to `longhorn-manager` master branch instead. See https://github.com/longhorn/longhorn/wiki/Repositories-for-contribution-guideline

**Comment by yasker** [comment]
Also, we can rename the directory to something else, e.g. `prerequisite` or something similar, since we can include both nfs and iscsi installation there.

**Comment by cclhsu** [comment]
Create PR https://github.com/longhorn/longhorn-manager/pull/820 in `longhorn-manager` and close this one.

**Pull request closed without merging**
