### PR TITLE
Add ability to customize Ingress PathType

### PR DESCRIPTION
**Pull request by e3b0c442**
#### Which issue(s) this PR fixes:

Issue #7889

#### What this PR does / why we need it:
Add ability to set PathType for Ingress resources via Helm chart

#### Special notes for your reviewer:
Partially addresses the linked issue.

ImplementationSpecific retained as default for backward compatibility.

### CODE REVIEW

**Review by shuo-wu — COMMENTED** [review]
Would you help add the corresponding option [here](https://github.com/longhorn/longhorn/blob/70523aaf1f60fd7228d46c46356497e901cfcf37/chart/questions.yaml#L825)?

Besides, plz add a Signed-off-by line for your commits. You can check [this](https://github.com/longhorn/longhorn/pull/7890/checks?check_run_id=21344857673) for details

**Review by shuo-wu — APPROVED** [review]

**Comment by jackmaninov** [comment]
Is there any movement on this? It affects me and I was hoping it could make the next release.

**Comment by shuo-wu** [comment]
@mantissahz Would you help validate this improvement before backport? Thank you!

**Comment by derekbit** [comment]
@mantissahz 
Do you think if we need to add the setting to our doc?

**Comment by mantissahz** [comment]
>Do you think if we need to add the setting to our doc?

Yes, we have to modify the document and README.md of the chart.
I am working on this.

for chart: https://github.com/longhorn/longhorn/pull/8398

**Pull request merged**
