### PR TITLE
chart: introduce guaranteed instance manager CPU setting for v2 volume

### PR DESCRIPTION
**Pull request by derekbit**
https://github.com/longhorn/longhorn/issues/7361

### CODE REVIEW

**Comment by innobead** [comment]
@derekbit Do we still need this PR? It seems duplicated of https://github.com/longhorn/longhorn/pull/7403.

**Comment by derekbit** [comment]
> @derekbit Do we still need this PR? It seems duplicated of #7403.

Yes, we can just keep https://github.com/longhorn/longhorn/pull/7403 if both PRs are merged.

**Comment by innobead** [comment]
> > @derekbit Do we still need this PR? It seems duplicated of #7403.
> 
> Yes, we can just keep #7403 if both PRs are merged.

Do you mean we don't need this PR if we merge #7403?

**Comment by derekbit** [comment]
> Do you mean we don't need this PR if we merge #7403?

Yes

**Comment by innobead** [comment]
Sounds good. Let's use #7403 instead.

**Pull request closed without merging**
