### PR TITLE
chore(scripts): add a script for updating chart/README.md

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue #

### CODE REVIEW

**Review by shuo-wu — APPROVED** [review]
In general LGTM

**Review by innobead — APPROVED** [review]

**Review by innobead — COMMENTED** [review]
After merging this PR, just noticed that as this is for the head branch, can we make the image tags for our components as branch-based?

For example, for 1.7.x, longhorn-manager should be `longhorn-manager:v1.7.x-head`? Also, we need to check if this change might affect our QA regression testing. 

cc @derekbit @longhorn/qa

**Comment by derekbit** [comment]
> After merging this PR, just noticed that as this is for the head branch, can we make the image tags for our components as branch-based?
> 
> For example, for 1.7.x, longhorn-manager should be `longhorn-manager:v1.7.x-head`? Also, we need to check if this change might affect our QA regression testing.
> 
> cc @derekbit @longhorn/qa

The script only updates the chart/README.md. I think we should only execute this script in the CI flow to make the longhorn-images.txt and README.md consistent. The update won't affect the QA regression testing.

**Comment by innobead** [comment]
yeah, true. only readme.

**Pull request merged**
