### PR TITLE
feat(lep): recurring filesystem trim design

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5186

### CODE REVIEW

**Review by shuo-wu — COMMENTED** [review]
NIT: May need to handle `deleteSnapMode` as well since it's meaningless to this.

**Comment by innobead** [comment]
> NIT: May need to handle `deleteSnapMode` as well since it's meaningless to this.

@shuo-wu can you explain a little more?

**Review by innobead — APPROVED** [review]
LGTM.

**Comment by innobead** [comment]
@mantissahz Please review this as well.

**Comment by mantissahz** [comment]
This LEP in general looks good to me and straightforward.

>I mean, the new field introduced by https://github.com/longhorn/longhorn-manager/pull/1708#event-8708770632.

I would like to clean up old snapshots that exceeds the retain number before create a new snapshot mandatorily because it is an abnormal situation. (so there is no new field introduced) as mentioned in https://github.com/longhorn/longhorn-manager/pull/1708#issuecomment-1463152193

**Pull request merged**
