### PR TITLE
chore: missing mkfsParams

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/pull/4909
https://github.com/longhorn/longhorn/issues/4642

### CODE REVIEW

**Comment by c3y1huang** [comment]
Already fixed. close.

**Comment by c3y1huang** [comment]
Actually the removal of `mkfsParams: ""` might not be intended. Reopen.

**Comment by weizhe0422** [comment]
I think the parameter 'mkfsParam' in 'deploy\longhorn.yaml' should be exists.

Also, I would like to ask why the if condition in 'template\storageclass.yaml' should be removed.

**Comment by c3y1huang** [comment]
> In addition, I would like to ask why the if condition in 'template\storageclass.yaml' should be removed.

When running [generate-longhorn-yaml.sh](https://github.com/longhorn/longhorn/blob/master/scripts/generate-longhorn-yaml.sh) `'mkfsParam` will not render `if .Values.persistence.defaultMkfsParams` is an empty value.

**Comment by c3y1huang** [comment]
> I think the parameter 'mkfsParam' in 'deploy\longhorn.yaml' should be exists.

After checking with @innobead , we will keep it the way it is. Closing.

**Pull request closed without merging**
