### PR TITLE
fix(support-bundle): version bump

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/6997
https://github.com/longhorn/longhorn/issues/7121

### CODE REVIEW

**Comment by c3y1huang** [comment]
[WIP] Publishing support-bundle-kit v0.0.30.

**Comment by c3y1huang** [comment]
@yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.30](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.30/images/sha256-d67211566dc0edd75ccbb78a94cf23381753c028d2a38b178c3e6de177441478?context=explore) to longhornio, thank you.

**Comment by yangchiu** [comment]
> @yangchiu please help to mirror [rancher/support-bundle-kit:v0.0.30](https://hub.docker.com/layers/rancher/support-bundle-kit/v0.0.30/images/sha256-d67211566dc0edd75ccbb78a94cf23381753c028d2a38b178c3e6de177441478?context=explore) to longhornio, thank you.

done.

**Comment by c3y1huang** [comment]
Bump up to v0.0.31 to include the fix for https://github.com/longhorn/longhorn/issues/7121.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
