### PR TITLE
chart: Update post upgrade job

### PR DESCRIPTION
**Pull request by shuo-wu**

### CODE REVIEW

**Comment by yasker** [comment]
Why do we need to change this?

**Comment by shuo-wu** [comment]
1. I don't want to fail the whole upgrade when the upgrader errors out for one time.

2. We can avoid changing the `backoffLimit` if we set a longer wait period in the upgrader. But we still need to set `toVersion` for the upgrader:
https://github.com/longhorn/longhorn-manager/blob/7cefc46ec36e193bf78f15d3c306dee4b011e751/app/post_upgrade.go#L88

**Comment by yasker** [comment]
After removing `deleteOrphanedReplicaJobs`, are we using fromVersion or toVersion for anything? If not, we can remove it for now.

**Comment by shuo-wu** [comment]
No. I will remove it.

**Pull request merged**
